Vagrant.configure("2") do |config|
  config.vm.box = "bseller/oracle-standard"
  config.vm.box_version = "1.0.0"
  config.vm.network = "private_network", type: "dhcp",
   name: "NAT"
config.vm.provider "virtualbox" do |vb|
   vb.name = M300DB01"
end